# Security Testing Workflow (Minimal Example)
# For CI security and dependency auditing

name: Security Testing

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    name: Python Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r . -ll || true
      - name: Run Safety for dependency vulnerabilities
        run: |
          pip install safety
          safety check || true
      - name: Semgrep (optional)
        run: |
          pip install semgrep
          semgrep scan --config=auto || true
      - name: Run Tests
        run: |
          pytest || python3 -m unittest discover -s tests || true

