# Security Testing Pipeline (GitHub Actions)
# Fixed version with correct `on` root key, cache paths, and directory creation
# Reference: https://github.com/Fayeblade1488/Vulne_Chatbot/edit/main/.github/workflows/security-testing.yml

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily security scan at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Test Level'
        required: true
        default: 'standard'
        type: choice
        options:
          - quick
          - standard
          - comprehensive
          - paranoid

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'
  RESULTS_RETENTION_DAYS: 30

jobs:
  setup:
    name: Setup and Cache Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate cache keys
        id: cache-keys
        run: |
          echo "key=deps-${{ hashFiles('**/requirements.txt', '**/package-lock.json') }}" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Ensure cache directories exist
        run: |
          mkdir -p ~/.cache/pip
          mkdir -p ~/.npm
          mkdir -p frontend/node_modules

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.npm
            frontend/node_modules
          key: ${{ steps.cache-keys.outputs.key }}

  # ... (rest of your jobs unchanged; see previous messages for full content)
